### ISSUE TITLE
app stuck at IPFS installation

### ISSUE THREAD

**Issue by bobinson** [vaultec81/3Speak-app#4]
- Downloaded version
- Installed on macOS 11.1 (with all the latest patches)
- The app is stuck

![image](https://user-images.githubusercontent.com/18070249/105340098-7440e780-5c03-11eb-93f8-cfdb1907aaea.png)

Console shows:

`Uncaught (in promise) {name: "TypeError", message: "Cannot read property 'has' of undefined", stack: "TypeError: Cannot read property 'has' of undefined…ntents/Resources/app/dist/main.prod.js:1054:68341"}`

```
"TypeError: Cannot read property 'has' of undefined
    at /Applications/3Speak-app.app/Contents/Resources/app/dist/main.prod.js:1190:75316
    at f (/Applications/3Speak-app.app/Contents/Resources/app/dist/main.prod.js:1061:6448)
    at Generator._invoke (/Applications/3Speak-app.app/Contents/Resources/app/dist/main.prod.js:1061:6201)
    at Generator.next (/Applications/3Speak-app.app/Contents/Resources/app/dist/main.prod.js:1061:6807)
    at r (/Applications/3Speak-app.app/Contents/Resources/app/dist/main.prod.js:8:2023)
    at s (/Applications/3Speak-app.app/Contents/Resources/app/dist/main.prod.js:8:2234)
    at /Applications/3Speak-app.app/Contents/Resources/app/dist/main.prod.js:8:2293
    at new Promise (<anonymous>)
    at /Applications/3Speak-app.app/Contents/Resources/app/dist/main.prod.js:8:2174
    at /Applications/3Speak-app.app/Contents/Resources/app/dist/main.prod.js:1190:75434
    at /Applications/3Speak-app.app/Contents/Resources/app/dist/main.prod.js:1054:68341"

```

**Comment by bobinson** [comment]
additionally tried to build from source and the `npm run dev` worked.

`npm run prod` gave the following:

![image](https://user-images.githubusercontent.com/18070249/105369704-cf390580-5c28-11eb-8667-ba04ef100941.png)


node version v12.19.1

**Comment by vaultec81** [comment]
Fix was already issued in dependency of interest and 6397e4f74b5c3c4235ad6929ad3ccb7be1c1af96
